/* GridLock UI. Data comes from data.js (generated by pipeline/overlaps.py). */
(() => {
  const D = window.GRID_DATA;
  const P = Object.fromEntries(D.projects.map(p => [p.id, p]));
  const $ = s => document.querySelector(s);
  const css = v => getComputedStyle(document.documentElement).getPropertyValue(v).trim();

  const TIER = {
    cross: { label: "Touching / crossing", short: "Touching", max: 0.1, base: 100, next: 85, color: "--t-cross",
             why: "Must coordinate: outage timing, crossing structures, shared terminal work" },
    row:   { label: "Under 1.6 km", short: "< 1.6 km", max: 1.6, base: 85, next: 65, color: "--t-row",
             why: "Can share the land itself: right-of-way, access roads, permits" },
    site:  { label: "Under 8 km", short: "< 8 km", max: 8, base: 65, next: 40, color: "--t-site",
             why: "Can share site logistics: laydown yards, material deliveries" },
    crew:  { label: "Under 40 km", short: "< 40 km", max: 40, base: 40, next: 0, color: "--t-crew",
             why: "Can share crews, cranes and contractors from one staging yard" },
  };
  const TIER_ORDER = ["cross", "row", "site", "crew"];
  const TIER_LO = { cross: 0, row: 0.1, site: 1.6, crew: 8 };
  const CONF = { high: 1, medium: 0.9, low: 0.75, none: 0 };
  const CONF_RANK = { high: 3, medium: 2, low: 1, none: 0 };
  const UTIL_COLOR = code => code === "DESC" ? css("--desc") : code === "GPC" ? css("--gpc") : css("--partner");
  const UTIL_NAME = p => p.utility_code === "DESC" ? "Dominion Energy SC" : p.utility;
  const fmtDate = s => s ? new Date(s + "T00:00").toLocaleDateString("en-US", { month: "short", year: "numeric" }) : "—";
  const money = n => n == null ? "—" : n >= 1e6 ? `$${(n / 1e6).toFixed(n >= 1e7 ? 1 : 2)}M` : `$${Math.round(n / 1e3)}k`;
  const esc = s => String(s ?? "").replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const day = s => new Date(s + "T00:00").getTime() / 864e5;

  /* ------------------------------------------------------------------ state */
  const store = (() => { try { return window.localStorage; } catch { return null; } })();
  const saved = (() => { try { return JSON.parse(store?.getItem("gridlock") || "{}"); } catch { return {}; } })();
  const state = {
    km: 40, gapYears: 10, tw: 40, overlapOnly: false, partners: false, minConf: 1, group: "pair",
    selected: null, tab: "list", assumptions: null, ...saved.filters,
  };
  const persist = () => { try { store?.setItem("gridlock", JSON.stringify({ filters: { km: state.km, gapYears: state.gapYears, tw: state.tw, overlapOnly: state.overlapOnly, partners: state.partners, minConf: state.minConf, group: state.group }, theme: document.documentElement.dataset.theme })); } catch {} };
  if (saved.theme) document.documentElement.dataset.theme = saved.theme;

  /* ------------------------------------------------------------------ scoring (mirrors pipeline/overlaps.py) */
  function score(o) {
    const t = TIER[o.tier];
    const geo = t.base - (t.base - t.next) * (o.distance_km - TIER_LO[o.tier]) / (t.max - TIER_LO[o.tier]);
    const timing = o.construction_overlap_days > 0 ? 1 : Math.max(0, 1 - o.isd_gap_days / (365 * 4));
    const conf = Math.min(CONF[o.a_conf], CONF[o.b_conf]);
    const w = state.tw / 100;
    return Math.round(geo * (1 - w + w * timing) * conf * 10) / 10;
  }

  function filtered() {
    let list = D.overlaps.filter(o =>
      o.distance_km <= state.km &&
      (state.gapYears >= 10 || o.isd_gap_days <= state.gapYears * 365) &&
      (!state.overlapOnly || o.construction_overlap_days > 0) &&
      (state.partners || o.b_utility_code === "GPC") &&
      Math.min(CONF_RANK[o.a_conf], CONF_RANK[o.b_conf]) >= state.minConf
    ).map(o => ({ ...o, s: score(o) }));
    list.sort((a, b) => b.s - a.s || a.distance_km - b.distance_km);
    if (state.group === "cluster") {
      const seen = new Set();
      list = list.filter(o => { const k = o.a; if (seen.has(k)) return false; seen.add(k); return true; });
    }
    list.forEach((o, i) => o.r = i + 1);
    return list;
  }

  /* ------------------------------------------------------------------ map */
  const map = L.map("map", { zoomControl: true, preferCanvas: false }).setView([33.0, -81.6], 7);
  let tiles;
  function setTiles() {
    const dark = getComputedStyle(document.documentElement).colorScheme === "dark";
    if (tiles) map.removeLayer(tiles);
    const base = `https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_${dark ? "Dark" : "Light"}_Gray_`;
    tiles = L.layerGroup([
      L.tileLayer(`${base}Base/MapServer/tile/{z}/{y}/{x}`, { maxZoom: 16, attribution: "Tiles &copy; Esri &mdash; Esri, HERE, Garmin, &copy; OpenStreetMap contributors" }),
      L.tileLayer(`${base}Reference/MapServer/tile/{z}/{y}/{x}`, { maxZoom: 16 }),
    ]).addTo(map);
    tiles.eachLayer(l => l.bringToBack());
  }
  setTiles();

  const statesLayer = L.layerGroup().addTo(map);
  const projLayer = L.layerGroup().addTo(map);
  const ovlLayer = L.layerGroup().addTo(map);
  const bufferLayer = L.layerGroup().addTo(map);
  const projShapes = {};   // id -> [layers]

  function drawStates() {
    statesLayer.clearLayers();
    for (const [code, rings] of Object.entries(D.states)) {
      for (const r of rings) L.polyline(r.map(([x, y]) => [y, x]), { color: css("--ink-3"), weight: 1, opacity: .45, dashArray: "2 4", interactive: false }).addTo(statesLayer);
    }
  }

  function popupHtml(p) {
    const w = p.window;
    return `<h4>${esc(p.name)}</h4>
      <div class="sub">${esc(UTIL_NAME(p))} · ${esc(p.sponsor || "DESC")} ${esc(p.source_id)}${p.zone ? " · zone " + p.zone : ""}</div>
      <div style="margin-top:6px">In service <b>${fmtDate(p.in_service)}</b>${w ? ` · build window from ${fmtDate(w.start)}` : ""}</div>
      ${p.cost_usd ? `<div>Budget <b>${money(p.cost_usd)}</b></div>` : ""}
      <div>Location <span class="conf ${p.location_confidence}">${p.location_confidence}</span></div>
      <div style="margin-top:6px"><a href="#" data-proj="${p.id}">Show overlaps for this project →</a></div>`;
  }

  function drawProjects(activeIds) {
    projLayer.clearLayers();
    for (const k in projShapes) delete projShapes[k];
    const show = D.projects.filter(p => p.geometry && (state.partners || ["DESC", "GPC"].includes(p.utility_code)));
    // Faint projects first so highlighted ones sit on top.
    show.sort((a, b) => (activeIds.has(a.id) ? 1 : 0) - (activeIds.has(b.id) ? 1 : 0));
    for (const p of show) {
      const on = activeIds.has(p.id);
      const color = UTIL_COLOR(p.utility_code);
      const style = { color, weight: on ? 4 : 2, opacity: on ? .95 : .35, dashArray: p.location_confidence === "low" ? "6 5" : null };
      const g = p.geometry, layers = [];
      if (g.type === "LineString") {
        layers.push(L.polyline(g.coordinates.map(([x, y]) => [y, x]), style));
        g.coordinates.forEach(([x, y]) => layers.push(L.circleMarker([y, x], { radius: on ? 4 : 2.5, color, weight: 1, fillColor: color, fillOpacity: on ? 1 : .4, opacity: on ? 1 : .4 })));
      } else {
        const [x, y] = g.coordinates;
        layers.push(L.circleMarker([y, x], { radius: on ? 7 : 4, color, weight: 2, fillColor: color, fillOpacity: on ? .55 : .2, opacity: on ? 1 : .45, dashArray: style.dashArray }));
      }
      layers.forEach(l => {
        l.bindPopup(popupHtml(p)).bindTooltip(esc(p.name), { sticky: true, direction: "top", opacity: .95 });
        l.addTo(projLayer);
      });
      projShapes[p.id] = layers;
    }
  }

  function drawOverlaps(list) {
    ovlLayer.clearLayers();
    for (const o of [...list].reverse()) {
      const color = css(TIER[o.tier].color);
      const a = [o.closest_a[1], o.closest_a[0]], b = [o.closest_b[1], o.closest_b[0]];
      const sel = state.selected === o.id;
      const faint = o.tier === "crew" && !sel;
      const line = L.polyline([a, b], { color, weight: sel ? 5 : faint ? 1.5 : 2.5, opacity: sel ? 1 : faint ? .45 : .85, dashArray: faint ? "2 5" : "5 5" });
      line.bindTooltip(`#${o.r} · ${o.distance_km.toFixed(1)} km · ${TIER[o.tier].short}`, { sticky: true });
      line.on("click", () => select(o.id, true));
      line.addTo(ovlLayer);
      if (o.distance_km < 0.2 || sel) L.circleMarker(a, { radius: sel ? 9 : 6, color, weight: 2, fillOpacity: 0 }).on("click", () => select(o.id, true)).addTo(ovlLayer);
    }
  }

  function drawBuffer(o) {
    bufferLayer.clearLayers();
    if (!o) return;
    // The 40 km "one staging yard" radius around the midpoint of the closest approach.
    const mid = [(o.closest_a[1] + o.closest_b[1]) / 2, (o.closest_a[0] + o.closest_b[0]) / 2];
    L.circle(mid, { radius: 40000, color: css("--accent"), weight: 1, opacity: .5, fillOpacity: .04, dashArray: "3 6", interactive: false }).addTo(bufferLayer);
    for (const t of ["site", "row"]) L.circle(mid, { radius: TIER[t].max * 1000, color: css(TIER[t].color), weight: 1, opacity: .6, fillOpacity: .05, interactive: false }).addTo(bufferLayer);
  }

  map.on("popupopen", e => {
    const a = e.popup.getElement().querySelector("[data-proj]");
    if (a) a.onclick = ev => { ev.preventDefault(); focusProject(a.dataset.proj); };
  });

  function focusProject(id) {
    const list = filtered().filter(o => o.a === id || o.b === id);
    if (list.length) select(list[0].id, true);
    else { map.closePopup(); alert("No overlaps pass the current filters for this project."); }
  }

  const VIEWS = { augusta: [[33.15, -82.45], [33.85, -81.55]], savannah: [[31.95, -81.5], [32.5, -80.75]] };
  document.querySelectorAll("[data-zoom]").forEach(b => b.onclick = () => {
    const v = b.dataset.zoom;
    if (v === "all") map.fitBounds(L.featureGroup(Object.values(projShapes).flat()).getBounds(), { padding: [20, 20] });
    else map.fitBounds(VIEWS[v]);
  });

  function drawLegend() {
    const t = TIER_ORDER.map(k => `<div class="li"><span class="sw dash" style="border-color:${css(TIER[k].color)}"></span>${TIER[k].label}</div>`).join("");
    $("#legend").innerHTML = `
      <h4>Planned projects</h4>
      <div class="li"><span class="sw" style="border-color:${css("--desc")}"></span>Dominion Energy SC</div>
      <div class="li"><span class="sw" style="border-color:${css("--gpc")}"></span>Georgia Power</div>
      ${state.partners ? `<div class="li"><span class="sw" style="border-color:${css("--partner")}"></span>GTC / MEAG / Dalton</div>` : ""}
      <div class="li"><span class="sw dash" style="border-color:${css("--ink-3")}"></span>Low-confidence location</div>
      <h4>Overlap (closest points)</h4>${t}`;
  }

  /* ------------------------------------------------------------------ list */
  function oppHtml(o) {
    const a = P[o.a], b = P[o.b];
    const t = TIER[o.tier];
    const timing = o.construction_overlap_days > 0
      ? `<span class="chip good">builds overlap ${Math.round(o.construction_overlap_days / 30)} mo</span>`
      : `<span class="chip ${o.isd_gap_days > 1095 ? "warn" : ""}">${(o.isd_gap_days / 365).toFixed(1)} yr apart</span>`;
    const weak = Math.min(CONF_RANK[o.a_conf], CONF_RANK[o.b_conf]) < 2 ? `<span class="chip warn">low-confidence location</span>` : "";
    return `<li class="opp ${state.selected === o.id ? "sel" : ""}" data-id="${o.id}">
      <div class="rank">${o.r}</div>
      <div class="pj"><i style="background:${css("--desc")}"></i><span title="${esc(a.name)}">${esc(a.name)}</span></div>
      <div class="score"><b>${o.s.toFixed(0)}</b><small>score</small></div>
      <div class="pj"><i style="background:${UTIL_COLOR(b.utility_code)}"></i><span title="${esc(b.name)}">${esc(b.name)}</span></div>
      <div class="meta">
        <span class="chip tier" style="background:${css(t.color)}">${t.short}</span>
        <span class="chip">${o.distance_km < 0.1 ? "shared point" : o.distance_km.toFixed(1) + " km"}</span>
        ${timing}${weak}
      </div></li>`;
  }

  function renderList(list) {
    $("#count").textContent = list.length;
    $("#opps").innerHTML = list.length ? list.map(oppHtml).join("") : `<li class="empty">No overlaps pass these filters.</li>`;
    $("#opps").querySelectorAll(".opp").forEach(li => {
      li.onclick = () => select(li.dataset.id, true);
      li.onmouseenter = () => hoverPair(li.dataset.id, true);
      li.onmouseleave = () => hoverPair(li.dataset.id, false);
    });
  }

  function hoverPair(id, on) {
    const o = D.overlaps.find(x => x.id === id);
    for (const pid of [o.a, o.b]) (projShapes[pid] || []).forEach(l => l.setStyle && l.setStyle({ weight: on ? 6 : (l instanceof L.CircleMarker ? 1 : 4) }));
  }

  /* ------------------------------------------------------------------ stats */
  function renderStats(list) {
    const desc = D.projects.filter(p => p.utility_code === "DESC");
    const gpc = D.projects.filter(p => p.utility_code === "GPC");
    const inPairs = new Set(list.flatMap(o => [o.a, o.b]));
    const tiers = TIER_ORDER.map(t => list.filter(o => o.tier === t).length);
    $("#stats").innerHTML = [
      [desc.length, "DESC projects"], [gpc.length, "Georgia Power"],
      [list.length, "overlapping pairs"],
      [`${tiers[0]} · ${tiers[1]} · ${tiers[2]}`, "touch · ROW · site"],
      [list.filter(o => o.construction_overlap_days > 0).length, "same build window"],
    ].map(([v, l]) => `<div class="stat"><b>${v}</b><span>${l}</span></div>`).join("");
  }

  /* ------------------------------------------------------------------ cost / impact model */
  const DEFAULTS = {
    landPerAcre: 15000,     // $/acre easement, rural coastal/Piedmont SC-GA
    rowShare: 0.35,         // fraction of the second corridor's width avoided by sharing
    permitting: 150000,     // $ for one joint environmental / permitting package instead of two
    yard: 300000,           // $ per laydown / staging yard (lease, grading, security, restoration)
    mobPct: 4,              // mobilization + demobilization as % of construction cost
    mobShare: 50,           // % of the smaller project's mobilization avoided by sharing crews
    crossing: 250000,       // $ avoided per coordinated crossing / shared-terminal outage
    perMile115: 2.0e6, perMile230: 3.0e6, perMile500: 4.5e6, perMile46: 1.2e6, subDefault: 8e6,
  };
  state.assumptions = { ...DEFAULTS, ...(saved.assumptions || {}) };

  const ROW_FT = kv => kv >= 500 ? 200 : kv >= 230 ? 150 : kv >= 115 ? 100 : 60;
  function projMiles(p) {
    if (p.line_miles) return p.line_miles;
    if (p.geometry?.type === "LineString") {
      const [[x1, y1], [x2, y2]] = p.geometry.coordinates;
      const R = 6371.0088, r = Math.PI / 180;
      const a = Math.sin((y2 - y1) * r / 2) ** 2 + Math.cos(y1 * r) * Math.cos(y2 * r) * Math.sin((x2 - x1) * r / 2) ** 2;
      return 2 * R * Math.asin(Math.sqrt(a)) / 1.609 * 1.15;   // 15% routing factor
    }
    return 0;
  }
  const EQUIPMENT = /REACTOR|TRANSFORMER|AUTO ?BANK|BANK|SUBSTATION|SUB|SWITCHING|CAPACITOR|STATCOM|BREAKER|RING BUS/i;
  function projCost(p, A) {
    if (p.cost_usd) return { v: p.cost_usd, est: false };
    const kv = p.voltage_kv || 115, mi = p.line_miles ?? (p.kind === "line" ? projMiles(p) : 0);
    const per = kv >= 500 ? A.perMile500 : kv >= 230 ? A.perMile230 : kv >= 115 ? A.perMile115 : A.perMile46;
    const equip = EQUIPMENT.test(p.name + " " + p.description) || !mi;
    const v = mi * per + (equip ? A.subDefault : 0);
    const basis = [mi ? `${mi.toFixed(1)} mi × ${money(per)}/mi (${kv} kV)` : "", equip ? `${money(A.subDefault)} substation / equipment work` : ""].filter(Boolean).join(" + ");
    return { v, est: true, basis };
  }

  function estimate(o) {
    const A = state.assumptions, a = P[o.a], b = P[o.b];
    const aligned = o.construction_overlap_days > 0;
    const ca = projCost(a, A), cb = projCost(b, A);
    const items = [];
    const tierIdx = TIER_ORDER.indexOf(o.tier);

    // Crews & equipment (every tier under 40 km)
    const smaller = Math.min(ca.v, cb.v);
    const mob = smaller * A.mobPct / 100 * A.mobShare / 100;
    items.push({ k: "Shared crews & equipment mobilization", v: mob, on: aligned,
      d: `${A.mobShare}% of ${A.mobPct}% mobilization on the smaller project (${money(smaller)})` });

    // Site logistics (< 8 km)
    if (tierIdx <= 2) items.push({ k: "One shared laydown / staging yard", v: A.yard, on: aligned, d: "one yard instead of two, plus consolidated material deliveries" });
    else items.push({ k: "Shared laydown yard", v: 0, on: false, na: true, d: "needs < 8 km" });

    // Right-of-way (< 1.6 km): only the stretch where the two lines actually run side by side.
    if (tierIdx <= 1) {
      const sharedMi = (o.parallel_km || 0) / 1.609;
      const width = Math.min(ROW_FT(a.voltage_kv || 115), ROW_FT(b.voltage_kv || 115));
      const acres = sharedMi * 5280 * width * A.rowShare / 43560;
      items.push({ k: "Shared right-of-way corridor & permits", v: acres * A.landPerAcre + A.permitting, on: true, acres,
        d: sharedMi > 0.05
          ? `${acres.toFixed(1)} acres avoided (${sharedMi.toFixed(1)} mi side by side × ${width} ft × ${Math.round(A.rowShare * 100)}%) + one joint permit package`
          : "lines meet at a shared facility rather than running side by side: one joint permit / siting package" });
    } else items.push({ k: "Shared right-of-way / permits", v: 0, on: false, na: true, d: "needs < 1.6 km" });

    // Touching / crossing
    if (o.tier === "cross") items.push({ k: "Coordinated outage & crossing / shared terminal", v: A.crossing, on: true, d: "one outage window and one crossing design instead of two" });

    const total = items.filter(i => i.on).reduce((s, i) => s + i.v, 0);
    const potential = items.filter(i => !i.na).reduce((s, i) => s + i.v, 0);
    return { items, total, potential, ca, cb, aligned };
  }

  /* ------------------------------------------------------------------ detail */
  function epHtml(e) {
    return `<div>${e.lat != null ? "●" : "○"} ${esc(e.name)} <span class="conf ${e.method === "rejected" ? "rejected" : e.confidence}">${e.method === "rejected" ? "not located" : e.confidence}</span>
      <span class="sub">${esc(e.note || (e.lat == null ? "not found in public map data" : ""))}</span></div>`;
  }
  function pcard(p) {
    const w = p.window;
    return `<div class="pcard" style="border-left-color:${UTIL_COLOR(p.utility_code)}">
      <div class="sub">${esc(UTIL_NAME(p))} · ${p.utility_code === "DESC" ? "SCRTP project " : "TEAMS #"}${esc(p.source_id)}${p.zone ? " · zone " + p.zone : ""} · PDF p.${p.source_page}</div>
      <h3>${esc(p.name)}</h3>
      <p>${esc(p.description || "—")}</p>
      <div class="sub">In service <b>${fmtDate(p.in_service)}</b> · ${esc(p.status)}${p.cost_usd ? ` · budget ${money(p.cost_usd)}` : " · cost redacted in public filing"}${p.line_miles ? ` · ${p.line_miles} mi` : ""}${p.voltage_kv ? ` · ${p.voltage_kv} kV` : ""}${w ? ` · window ${fmtDate(w.start)} → ${fmtDate(w.in_service)}` : ""}</div>
      <div class="eps">${p.endpoints.map(epHtml).join("")}</div>
    </div>`;
  }

  function miniGantt(o) {
    const a = P[o.a], b = P[o.b];
    const all = [a, b].flatMap(p => [day(p.window.start), day(p.window.in_service)]);
    const lo = Math.min(...all) - 90, hi = Math.max(...all) + 90;
    const x = v => `${((v - lo) / (hi - lo) * 100).toFixed(2)}%`;
    const w = (s, e) => `${((e - s) / (hi - lo) * 100).toFixed(2)}%`;
    const row = p => {
      const s = day(p.window.start), c = day(p.window.construction_start), e = day(p.window.in_service), col = UTIL_COLOR(p.utility_code);
      return `<div class="mg-row"><span>${p.utility_code === "DESC" ? "DESC" : "Georgia"}</span><div class="mg-track">
        <div class="mg-bar" style="left:${x(s)};width:${w(s, e)};background:${col}"></div>
        <div class="mg-bar c" style="left:${x(c)};width:${w(c, e)};background:${col}"></div>
        <div class="mg-isd" style="left:${x(e)}" title="In service ${fmtDate(p.window.in_service)}"></div></div></div>`;
    };
    const oc = Math.max(day(a.window.construction_start), day(b.window.construction_start));
    const oe = Math.min(day(a.window.in_service), day(b.window.in_service));
    const ovl = oe > oc ? `<div class="mg-row"><span>overlap</span><div class="mg-track"><div class="mg-ovl" style="left:${x(oc)};width:${w(oc, oe)}"></div></div></div>` : "";
    const y0 = new Date(lo * 864e5).getFullYear(), y1 = new Date(hi * 864e5).getFullYear();
    return `<div class="mini-gantt">${row(a)}${row(b)}${ovl}
      <div class="mg-axis"><span>${y0}</span><span>${Math.round((y0 + y1) / 2)}</span><span>${y1}</span></div></div>
      <p class="note">Faint bar = planning window (start date → in service). Solid bar = final ${D.params.construction_months} months of field construction. Black tick = in-service date.</p>`;
  }

  function renderDetail() {
    const o = filtered().find(x => x.id === state.selected) || (() => { const r = D.overlaps.find(x => x.id === state.selected); return r && { ...r, s: score(r), r: "–" }; })();
    if (!o) { $("#detail").innerHTML = `<p class="empty">Select an opportunity.</p>`; return; }
    const a = P[o.a], b = P[o.b], t = TIER[o.tier], E = estimate(o);
    const tierIdx = TIER_ORDER.indexOf(o.tier);
    const shares = TIER_ORDER.map(k => `<li class="${TIER_ORDER.indexOf(k) >= tierIdx ? "" : "off"}">${TIER[k].why}</li>`).join("");
    const A = state.assumptions;
    const inp = (k, label, step = 1) => `<label>${label}<input type="number" data-a="${k}" value="${A[k]}" step="${step}"></label>`;
    const timingText = o.construction_overlap_days > 0
      ? `Field construction overlaps for about <b>${Math.round(o.construction_overlap_days / 30)} months</b>. Crews could move between the two jobs without re-mobilizing.`
      : `The in-service dates are <b>${(o.isd_gap_days / 365).toFixed(1)} years</b> apart. Resource sharing needs one project to shift, so savings are shown as <i>potential</i>.`;

    $("#detail").innerHTML = `
      <button class="back" id="back">← All opportunities</button>
      <div class="d-head">
        <div><div class="sub" style="color:var(--ink-3);font-size:12px">Opportunity #${o.r} · ${o.id}</div>
          <h2>${esc(a.name.split(":")[0])} ⟷ ${esc(b.name.replace(/^\w+:\s*/, ""))}</h2></div>
        <div class="big">${o.s.toFixed(0)}<small>score / 100</small></div>
      </div>
      <div class="kpis">
        <div class="kpi"><b style="color:${css(t.color)}">${o.distance_km < 0.1 ? "0 km" : o.distance_km.toFixed(2) + " km"}</b><span>closest approach · ${t.label.toLowerCase()}</span></div>
        <div class="kpi"><b>${o.isd_gap_days.toLocaleString()} d</b><span>between in-service dates</span></div>
        <div class="kpi"><b>${money(E.aligned ? E.total : E.potential)}</b><span>${E.aligned ? "est. savings" : "potential savings"}</span></div>
      </div>
      <section class="block"><h3>What the two utilities could share</h3><ul class="share">${shares}</ul></section>
      <section class="block"><h3>Timeline</h3><p class="note" style="margin-bottom:8px;color:var(--ink-2)">${timingText}</p>${miniGantt(o)}</section>
      <section class="block cost"><h3>Rough cost / impact estimate</h3>
        <table>${E.items.map(i => `<tr class="${i.na ? "na" : ""}"><td>${i.k}<small>${esc(i.d)}${!i.na && !i.on ? " · only if schedules are aligned" : ""}</small></td><td>${i.na ? "—" : (i.on ? "" : "(") + money(i.v) + (i.on ? "" : ")")}</td></tr>`).join("")}
          <tr class="total"><td>${E.aligned ? "Estimated savings as scheduled" : "Estimated savings as scheduled"}</td><td>${money(E.total)}</td></tr>
          ${E.potential > E.total ? `<tr><td>Potential if build windows are aligned</td><td>${money(E.potential)}</td></tr>` : ""}
        </table>
        <p class="note">Project costs: DESC ${money(E.ca.v)}${E.ca.est ? ` (est. ${esc(E.ca.basis)})` : " (filed budget)"} · Georgia ${money(E.cb.v)}${E.cb.est ? ` (est. ${esc(E.cb.basis)}; Georgia Power costs are redacted in the public IRP)` : ""}.
          Planning-level assumptions below. Edit them and the estimate updates.</p>
        <div class="assump">
          ${inp("mobPct", "Mobilization % of cost", .5)}${inp("mobShare", "% of mobilization shared", 5)}
          ${inp("yard", "Laydown yard $", 10000)}${inp("landPerAcre", "Easement $/acre", 1000)}
          ${inp("rowShare", "ROW width saved (0-1)", .05)}${inp("permitting", "Joint permitting $", 10000)}
          ${inp("crossing", "Coordinated crossing $", 10000)}${inp("subDefault", "Substation work $ (GA est.)", 500000)}
          ${inp("perMile115", "115 kV $/mile (GA est.)", 100000)}${inp("perMile230", "230 kV $/mile (GA est.)", 100000)}
        </div>
        <button class="ghost" id="reset-a" style="justify-self:start">Reset assumptions</button>
      </section>
      <section class="block"><h3>The two projects</h3><div style="display:grid;gap:8px">${pcard(a)}${pcard(b)}</div></section>`;

    $("#back").onclick = () => setTab("list");
    $("#reset-a").onclick = () => { state.assumptions = { ...DEFAULTS }; saveAssump(); renderDetail(); };
    $("#detail").querySelectorAll("[data-a]").forEach(el => el.onchange = () => {
      const v = parseFloat(el.value); if (!isNaN(v)) { state.assumptions[el.dataset.a] = v; saveAssump(); renderDetail(); }
    });
  }
  function saveAssump() { try { const s = JSON.parse(store?.getItem("gridlock") || "{}"); s.assumptions = state.assumptions; store?.setItem("gridlock", JSON.stringify(s)); } catch {} }

  /* ------------------------------------------------------------------ gantt tab */
  function renderGantt(list) {
    const ids = [...new Set(list.flatMap(o => [o.a, o.b]))].map(id => P[id]).filter(p => p.window);
    if (!ids.length) { $("#gantt").innerHTML = `<p class="empty">No overlaps pass these filters.</p>`; return; }
    // Group by area: which DESC project cluster each belongs to, north (Augusta) vs south (Savannah).
    const area = p => { const c = p.geometry.type === "Point" ? p.geometry.coordinates : p.geometry.coordinates[0]; return c[1] > 32.8 ? "Augusta / Aiken area" : "Savannah / Lowcountry area"; };
    const groups = {};
    ids.forEach(p => (groups[area(p)] ||= []).push(p));
    const all = ids.flatMap(p => [day(p.window.start), day(p.window.in_service)]);
    const lo = Math.min(...all) - 60, hi = Math.max(...all) + 60;
    const x = v => ((v - lo) / (hi - lo) * 100);
    const y0 = new Date(lo * 864e5).getFullYear() + 1, y1 = new Date(hi * 864e5).getFullYear();
    const ticks = []; for (let y = y0; y <= y1; y++) ticks.push(`<span style="left:${x(day(`${y}-01-01`)).toFixed(2)}%">${String(y).slice(2)}'</span>`);
    const today = x(Date.now() / 864e5);
    let html = `<div class="g-head"><h3 style="font-size:13px">Build windows of every project in a flagged overlap</h3></div>
      <p class="note" style="margin-bottom:8px">Hover a row to see its partners on the map. Click it to open its top opportunity. Solid = final ${D.params.construction_months} months of construction.</p>
      <div class="g-axis"><span></span><div class="ticks">${ticks.join("")}</div></div><div class="g-grid">`;
    for (const [g, ps] of Object.entries(groups).sort()) {
      html += `<div class="g-group">${g}</div>`;
      ps.sort((a, b) => a.utility_code.localeCompare(b.utility_code) || a.window.in_service.localeCompare(b.window.in_service));
      for (const p of ps) {
        const col = UTIL_COLOR(p.utility_code);
        const s = x(day(p.window.start)), c = x(day(p.window.construction_start)), e = x(day(p.window.in_service));
        html += `<div class="g-row" data-pid="${p.id}"><span class="nm" title="${esc(p.name)}"><i style="background:${col}"></i>${esc(p.name.replace(/^\w+:\s*/, ""))}</span>
          <div class="mg-track"><div class="mg-bar" style="left:${s}%;width:${e - s}%;background:${col}"></div>
          <div class="mg-bar c" style="left:${c}%;width:${e - c}%;background:${col}"></div>
          ${today > 0 && today < 100 ? `<div class="g-today" style="left:${today}%"></div>` : ""}</div></div>`;
      }
    }
    $("#gantt").innerHTML = html + "</div>";
    $("#gantt").querySelectorAll(".g-row").forEach(r => {
      const pid = r.dataset.pid;
      const partners = new Set(list.filter(o => o.a === pid || o.b === pid).flatMap(o => [o.a, o.b]));
      r.onmouseenter = () => { partners.forEach(id => (projShapes[id] || []).forEach(l => l.setStyle?.({ weight: 7 }))); $("#gantt").querySelectorAll(".g-row").forEach(o => o.classList.toggle("hl", partners.has(o.dataset.pid))); };
      r.onmouseleave = () => { renderMapOnly(); $("#gantt").querySelectorAll(".g-row").forEach(o => o.classList.remove("hl")); };
      r.onclick = () => focusProject(pid);
    });
  }

  /* ------------------------------------------------------------------ orchestration */
  let current = [];
  function renderMapOnly() {
    const active = new Set(current.flatMap(o => [o.a, o.b]));
    drawProjects(active); drawOverlaps(current);
  }
  function render() {
    current = filtered();
    renderStats(current); renderList(current); renderMapOnly(); drawLegend();
    if (state.tab === "timeline") renderGantt(current);
    if (state.tab === "detail") renderDetail();
    persist();
  }

  function select(id, zoom) {
    state.selected = id;
    const o = D.overlaps.find(x => x.id === id);
    $("#tab-detail").disabled = false;
    setTab("detail");
    drawOverlaps(current); drawBuffer(o);
    document.querySelectorAll(".opp").forEach(li => li.classList.toggle("sel", li.dataset.id === id));
    if (zoom) {
      const layers = [...(projShapes[o.a] || []), ...(projShapes[o.b] || [])];
      if (layers.length) map.fitBounds(L.featureGroup(layers).getBounds().pad(0.35), { maxZoom: 12 });
    }
  }

  function setTab(t) {
    state.tab = t;
    document.querySelectorAll(".tabs button").forEach(b => b.classList.toggle("active", b.dataset.tab === t));
    document.querySelectorAll(".panel").forEach(p => p.classList.toggle("active", p.id === `panel-${t}`));
    $("#filters").classList.toggle("hidden", t === "detail");
    if (t === "timeline") renderGantt(current);
    if (t === "detail") renderDetail();
    if (t !== "detail") drawBuffer(null);
  }
  document.querySelectorAll(".tabs button").forEach(b => b.onclick = () => !b.disabled && setTab(b.dataset.tab));

  /* filters */
  const bind = (sel, key, parse, out) => {
    const el = $(sel);
    if (el.type === "checkbox") el.checked = state[key]; else el.value = state[key];
    const upd = () => { state[key] = parse(el); if (out) out(); render(); };
    el.addEventListener(el.type === "range" ? "input" : "change", upd);
  };
  const outs = () => {
    $("#o-km").textContent = `${state.km} km`;
    $("#o-gap").textContent = state.gapYears >= 10 ? "any" : `${state.gapYears} yr`;
    $("#o-tw").textContent = `${state.tw}%`;
  };
  bind("#f-km", "km", e => +e.value, outs);
  bind("#f-gap", "gapYears", e => +e.value, outs);
  bind("#f-tw", "tw", e => +e.value, outs);
  bind("#f-overlap", "overlapOnly", e => e.checked);
  bind("#f-partners", "partners", e => e.checked);
  bind("#f-conf", "minConf", e => +e.value);
  bind("#f-group", "group", e => e.value);
  outs();

  /* theme */
  $("#btn-theme").onclick = () => {
    const dark = getComputedStyle(document.documentElement).colorScheme === "dark";
    document.documentElement.dataset.theme = dark ? "light" : "dark";
    setTiles(); drawStates(); render(); if (state.selected && state.tab === "detail") drawBuffer(D.overlaps.find(x => x.id === state.selected));
  };

  /* export */
  $("#btn-export").onclick = () => {
    const rows = [["rank", "score", "tier", "distance_km", "isd_gap_days", "construction_overlap_days", "desc_project", "desc_in_service", "georgia_project", "georgia_sponsor", "georgia_in_service", "est_savings_as_scheduled", "est_savings_if_aligned"]];
    current.forEach(o => { const E = estimate(o); rows.push([o.r, o.s, o.tier, o.distance_km, o.isd_gap_days, o.construction_overlap_days, P[o.a].name, P[o.a].in_service, P[o.b].name, P[o.b].sponsor, P[o.b].in_service, Math.round(E.total), Math.round(E.potential)]); });
    const csv = rows.map(r => r.map(v => `"${String(v).replace(/"/g, '""')}"`).join(",")).join("\n");
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" }));
    a.download = "gridlock_opportunities.csv"; a.click();
  };

  /* methodology */
  $("#btn-method").onclick = () => {
    const n = D.projects.length, located = D.projects.filter(p => p.geometry).length;
    const conf = c => D.projects.filter(p => p.location_confidence === c).length;
    $("#method-body").innerHTML = `
      <p>GridLock reads each utility's public plan, finds every project's real-world location, and measures how close each Dominion Energy SC project comes to each Georgia project.</p>
      <h3>1 · Data (public filings only)</h3>
      <table><tr><th>Utility</th><th>Source</th><th>Projects</th></tr>
        <tr><td>Dominion Energy SC</td><td>SCRTP "Planned Transmission Projects $2M and above", 2024–2028</td><td>${D.projects.filter(p => p.utility_code === "DESC").length}</td></tr>
        <tr><td>Georgia Power (+ SAV)</td><td>2025 IRP Vol. 3 public disclosure, GA ITS Ten-Year Plan, Table 2 plus per-project detail pages</td><td>${D.projects.filter(p => p.utility_code === "GPC").length}</td></tr>
        <tr><td>GTC · MEAG · Dalton</td><td>Same GA ITS table (optional layer)</td><td>${D.projects.filter(p => !["DESC", "GPC"].includes(p.utility_code)).length}</td></tr></table>
      <p>Costs and supporting statements redacted in the public filing stay redacted. No CEII data is used.</p>
      <h3>2 · Locating projects</h3>
      <p>Each project name is split into its named substations (e.g. <code>Okatie-Bluffton 115kV</code> → Okatie, Bluffton). Each substation is matched, in priority order, to:
        (1) hand-verified coordinates with a cited source, (2) OpenStreetMap substations and plants (Overpass API), preferring the utility's own tagged assets inside the correct state polygon, (3) Nominatim geocoding.
        A location is rejected if it falls outside the project's state, lies more than 100 km from its Georgia planning zone, or makes a line implausibly long for its stated mileage.
        Lines are drawn as straight segments between substations, the same approximation the challenge brief uses.</p>
      <p>${located} of ${n} projects located · ${conf("high")} high, ${conf("medium")} medium, ${conf("low")} low confidence. Low-confidence projects are drawn dashed and down-weighted in the score.</p>
      <h3>3 · Overlap</h3>
      <p><b>Geographic (primary):</b> the shortest distance between the two geometries' closest points, not their centres. Pairs 40 km or more apart are ignored. Tiers: touching/crossing (&lt; 0.1 km) · &lt; 1.6 km · &lt; 8 km · &lt; 40 km.</p>
      <p><b>Timeline (secondary):</b> each project gets a planning window (Georgia start date, or DESC's first budget year with spend) and a construction window (the final ${D.params.construction_months} months before in-service). We record the days between in-service dates and the days of construction overlap.</p>
      <p><b>Score:</b> <code>geo × ((1 − w) + w × timing) × confidence</code>. <code>geo</code> is 100 → 0 across the tiers by distance. <code>timing</code> is 1 if construction windows overlap, otherwise it fades to 0 over a 4-year gap. <code>w</code> is the timeline-weight slider (default 40%). <code>confidence</code> is 1 / 0.9 / 0.75 for high / medium / low location confidence.</p>
      <h3>4 · Cost / impact</h3>
      <p>For each pair the estimate adds up whichever mechanisms its tier allows: shared mobilization of crews and equipment, one laydown yard instead of two, a shared right-of-way corridor and joint permitting, and a single coordinated outage or crossing. Savings count "as scheduled" only when construction windows overlap. Otherwise they are shown as potential. Every assumption is editable in the detail view.</p>
      <h3>Known limitations</h3>
      <p>Straight lines are not real routes. "Hooks" (DESC) is not in public map data, so it is estimated near Clarks Hill, SC from the PDF's 2.3-mile description. New substations (Dawson, Scout, Big Ogeechee) are placed from their descriptions. Georgia Power cost figures are redacted, so they are estimated per mile.</p>
      <p class="note">Data generated ${D.generated}. Base map © OpenStreetMap contributors, © CARTO.</p>`;
    $("#method").showModal();
  };
  $("#method").addEventListener("click", e => { if (e.target.matches("[data-close]") || e.target === $("#method")) $("#method").close(); });

  drawStates();
  render();
  map.fitBounds([[31.9, -82.6], [34.4, -79.6]]);
  // Deep links: #sel=OVL-002&tab=timeline&zoom=savannah
  const h = Object.fromEntries(new URLSearchParams(location.hash.slice(1)));
  const first = h.sel || (!saved.filters && current[0]?.id);
  if (first && D.overlaps.some(o => o.id === first)) select(first, !!h.sel);
  if (h.tab) setTab(h.tab);
  if (VIEWS[h.zoom]) map.fitBounds(VIEWS[h.zoom]);
  window.addEventListener("hashchange", () => location.reload());
})();
